#!/usr/bin/env bash
data_dir=$1
keystore_dir=$2
network=$3
identity=$4

chmod -x /etc/update-motd.d/* && touch /etc/motd
cat /opt/extras/banner > /etc/motd
wanip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
tomokey=`ls $keystore_dir/UTC*`
sleep 5

gr='\033[0;32m'
nc='\033[0m'

tomopid="$(pgrep tomo)"
tomostatus="is running with PID $tomopid"
if [ -z "${tomopid}" ]; then tomostatus="is not running  . . "; fi

echo -e "TomoChain Deployment Details\n" >> /etc/motd
echo "Node Type : Full Node on Network $network" >> /etc/motd
echo -e "Status : ${gr}TomoChain $tomostatus ${nc}" >> /etc/motd
echo "WAN IP : $wanip" >> /etc/motd
echo "Tomo KeyFile : $tomokey"  >> /etc/motd
echo "Tomo Key Passphrase File : /opt/keys/pass.txt" >> /etc/motd
echo "Tomo Keystore Directory : $keystore_dir" >> /etc/motd
echo "Tomo Data Directory : $data_dir" >> /etc/motd
echo "Tomo Node Identity : $identity" >> /etc/motd
echo -e "Hosting : ThreeFold Grid\n\n" >> /etc/motd
