#!/usr/bin/env bash
data_dir=$1
nodeid=$2
enodeid=$3

chmod -x /etc/update-motd.d/* && rm -f /etc/update-motd.d/* && touch /etc/motd
cat /opt/extras/banner > /etc/motd
wanip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
sleep 5

gr='\033[0;32m'
nc='\033[0m'
yc='\033[1;33m'

heimpid="$(pgrep heimdall | sed 's/^\|$/"/g'|paste -sd, -)"
heimstatus="is running with PID $heimpid "
if [ -z "${heimpid}" ]; then heimstatus="is not running  . . "; fi

borpid="$(pgrep bor)"
borstatus="is running with PID $borpid "
if [ -z "${borpid}" ]; then borstatus="is not running  . . "; fi

echo -e "Matic Node Deployment Details\n" >> /etc/motd
echo -e "${yc}Node Type : Full Node on Mainnet${nc}" >> /etc/motd
echo -e "Bor Service : ${gr}Bor $borstatus ${nc}" >> /etc/motd
echo -e "Heimdall Service : ${gr}Heimdall $heimstatus ${nc}" >> /etc/motd
echo "Matic Data : $data_dir" >> /etc/motd
echo "WAN IP : $wanip" >> /etc/motd
echo "NodeID : $nodeid"  >> /etc/motd
echo "EnodeID : $enodeid"  >> /etc/motd
echo "For Validator : $enodeid@$wanip:30303"  >> /etc/motd
echo -e "Hosting : ThreeFold Grid\n\n" >> /etc/motd
