apiVersion: v1
kind: Service
metadata:
  name: {{ include "tomo.fullname" . }}
  labels:
    {{- include "tomo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "tomo.selectorLabels" . | nindent 4 }}
