apiVersion: v1
kind: PersistentVolume
metadata:
  name: dgb-volume
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dgb"
