#!/usr/bin/env bash
shard=$1
network=$2
chmod -x /etc/update-motd.d/* && touch /etc/motd
cat /opt/extras/banner > /etc/motd
wanip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
blskey=`ls /opt/keys/*.key`

echo -e "Harmony Deployment Details\n" >> /etc/motd
echo "Node Type : Full Node on $network" >> /etc/motd
echo "WAN IP : $wanip" >> /etc/motd
echo "BLS KeyFile : $blskey"  >> /etc/motd
echo "BLS Key Passphrase File : /opt/keys/keypass.txt" >> /etc/motd
echo "Shard : $shard" >> /etc/motd
echo -e "Hosting : ThreeFold Grid\n\n" >> /etc/motd
