#!/usr/bin/env bash
data_dir=$1
nodeid=$2
enodeid=$3
address=$4

chmod -x /etc/update-motd.d/* && rm -f /etc/update-motd.d/* && touch /etc/motd
cat /opt/extras/banner > /etc/motd
wanip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
sleep 5

gr='\033[0;32m'
nc='\033[0m'
yc='\033[1;33m'

heimpid="$(pgrep heimdall | sed 's/^\|$/"/g'|paste -sd, -)"
heimstatus="is running with PID $heimpid "
if [ -z "${heimpid}" ]; then heimstatus="is not running  . . "; fi

borpid="$(pgrep bor)"
borstatus="is running with PID $borpid "
if [ -z "${borpid}" ]; then borstatus="is not running  . . "; fi

echo -e "Matic Node Deployment Details\n" >> /etc/motd
echo -e "${yc}Node Type : Validator Node on Mainnet${nc}" >> /etc/motd
echo -e "Bor Service : ${gr}Bor $borstatus ${nc}" >> /etc/motd
echo -e "Heimdall Service : ${gr}Heimdall $heimstatus ${nc}" >> /etc/motd
echo "Validator Address : $address" >> /etc/motd
echo "Matic Configuration Directory : $data_dir" >> /etc/motd
echo "WAN IP : $wanip" >> /etc/motd
echo "NodeKey : $nodeid"  >> /etc/motd
echo "enodeID : $enodeid"  >> /etc/motd
echo "Add to Sentry : $enodeid@$wanip"  >> /etc/motd
echo -e "Hosting : ThreeFold Grid\n\n" >> /etc/motd
