#!/usr/bin/expect 

set timeout 2000
spawn heimdallcli generate-keystore 22092f74b7844a18f081cadb29d1e3e44388d027ee74a1996ef4323273d0b4bb --home /matic-data/heimdalld
expect "Passphrase"
send -- "tf2020\r"
sleep 1
expect "Repeat passphrase"
send -- "tf2020\r"
sleep 1
expect eof
